import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../app/globals.css";
import { connectToDB } from "@/lib/mongoose";

const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import SessionProvider from "../provider/SessionProvider";
import Navbar from "@/components/shared/Topbar";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create nextjs app",
};
connectToDB();

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  console.log("sds",session)
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-dark-1`}>
        <SessionProvider session={session}>
          <div className="w-ful flex justify-center items-center min-h-screen">
          <Navbar />
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
