import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../../app/globals.css";
import { connectToDB } from "@/lib/mongoose";

const inter = Inter({ subsets: ["latin"] });
import { getServerSession } from "next-auth";
import SessionProvider from "../../provider/SessionProvider";
import Navbar from "@/components/shared/Topbar";
import { Toaster } from "@/components/ui/toaster"
import LeftSidebar from "@/components/shared/LeftSidebar";
import { redirect } from "next/navigation";
import { ThemeProvider } from "@/provider/theme-provider";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create nextjs app",
};
connectToDB();

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  if (session) {
    redirect(`profile/${session.user?.name}`);
  }
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-dark-1`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            <section className='main-container'>
              <div className='w-full max-w-4xl'>
                {children}
              </div>
            </section>
            <Toaster />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
